apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: minio-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce #the volume can be mounted as read-write by a single node. Can allow multiple pods to access the volume when the pods are running on the same node
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /home/helen/Programming/ml_deployment/ml_deploy/data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
