apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: minio-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
# storageClassName: local
  storageClassName: manual
  hostPath:
    path: "/home/minio" 