apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce #the volume can be mounted as read-write by a single node. Can allow multiple pods to access the volume when the pods are running on the same node.
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      app: minio-storage